stages:
    - build
    - upload
    - release

variables:
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nvim-multiwindow/${CI_COMMIT_TAG}"

build:mac:
  stage: build
  image: golang:1.22
  script: 
    - env GOOS=darwin GOARCH=arm64 go build -o nvim-multiwindow-darwin-arm64 cmd/nvim-multiwindow/main.go
  artifacts:
      paths:
          - nvim-multiwindow-darwin-arm64

build:windows:
  stage: build
  image: golang:1.22
  script: 
    - env GOOS=windows GOARCH=amd64 go build -o nvim-multiwindow-windows-amd64 cmd/nvim-multiwindow/main.go
  artifacts:
      paths:
          - nvim-multiwindow-windows-amd64

build:linux:
  stage: build
  image: golang:1.22
  script: 
    - env GOOS=linux GOARCH=amd64 go build -o nvim-multiwindow-linux-amd64 cmd/nvim-multiwindow/main.go
  artifacts:
      paths:
          - nvim-multiwindow-linux-amd64

upload:
    stage: upload
    image: curlimages/curl:latest
    script:
        - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file nvim-multiwindow-darwin-arm64 ${PACKAGE_REGISTRY_URL}/nvim-multiwindow-darwin-arm64'
        - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file nvim-multiwindow-windows-amd64 ${PACKAGE_REGISTRY_URL}/nvim-multiwindow-windows-amd64'
        - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file nvim-multiwindow-linux-amd64 ${PACKAGE_REGISTRY_URL}/nvim-multiwindow-linux-amd64'
