vim.keymap.set('n', '<leader>N', function()
  local cwd = vim.fn['getcwd']()
  local file = vim.fn.expand('%')
  os.execute(string.format("%s/nvim-multiwindow %s", cwd, file))
end, { noremap = true, silent = true, desc = "[N]vimMultiwindow: New Window" })
